# Generated by Django 5.1 on 2025-04-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authentication_type',
            field=models.CharField(choices=[('password', 'Password'), ('oauth', 'OAuth')], default='password', max_length=50),
        ),
    ]
