# Generated by Django 5.1 on 2025-04-20 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='offert',
            field=models.ForeignKey(limit_choices_to={'company': models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selled_offerts', to='api.company')}, on_delete=django.db.models.deletion.PROTECT, to='marketplace.offert'),
        ),
    ]
