# Generated by Django 5.2 on 2025-08-19 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_url', models.CharField(max_length=250)),
                ('endpoint', models.CharField(max_length=100)),
                ('api_key', models.CharField(blank=True, max_length=150, null=True)),
                ('headers', models.JSONField(blank=True, null=True)),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='APIParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('bool', 'Bool'), ('date', 'Date')])),
                ('format', models.CharField(max_length=50, blank=True, null=True)),
                ('api_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='apis.apiconfig')),
            ],
        ),
    ]
