# Generated by Django 5.2 on 2025-05-06 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0002_user_authentication_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='money',
        ),
    ]
