# Generated by Django 5.2 on 2025-08-17 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('symbol', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='MonetaryIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20)),
                ('api_url', models.CharField(max_length=300)),
                ('api_config', models.JSONField()),
                ('data_frequency', models.TextField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('annualy', 'Annualy')])),
                ('calculation_type', models.TextField(choices=[('accumulated', 'Accumulated'), ('calculated', 'Calculated')])),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.currency')),
            ],
        ),
    ]
