# Generated by Django 5.2 on 2025-08-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.RunPython()
    ]
