# Generated by Django 5.2 on 2025-08-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_populate_currency_monetary_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monetaryindex',
            name='api_url',
        ),
        migrations.AlterField(
            model_name='monetaryindex',
            name='api_config',
            field=models.JSONField(),
        ),
    ]
