# Generated by Django 5.2 on 2025-08-19 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
        ('finances', '0003_remove_monetaryindex_api_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monetaryindex',
            name='api_config',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='apis.apiconfig'),
        ),
    ]
