# Generated by Django 5.2 on 2025-05-15 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
        ('offerts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bought_offerts', to=settings.AUTH_USER_MODEL)),
                ('offert', models.ForeignKey(limit_choices_to={'company': models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selled_offerts', to='companies.company')}, on_delete=django.db.models.deletion.PROTECT, to='offerts.offert')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selled_offerts', to='companies.company')),
            ],
        ),
    ]
