# Generated by Django 5.2 on 2025-07-27 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_alter_offert_created_by'),
        ('transactions', '0002_remove_transaction_offert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='investment_offer',
            field=models.ForeignKey(limit_choices_to={'company': models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selled_offerts', to='companies.company')}, on_delete=django.db.models.deletion.PROTECT, to='offers.investmentoffer'),
        ),
    ]
