# Generated by Django 5.2 on 2025-07-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_rename_date_transaction_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='buyer',
            new_name='created_by',
        ),
    ]
