# Generated by Django 5.2 on 2025-07-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.TextField(choices=[('STANDARD', 'Standard'), ('ADMIN', 'Admin'), ('COMPANY', 'Company')], default='STANDARD'),
        ),
    ]
