# Generated by Django 5.2 on 2025-08-01 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_alter_offert_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentoffer',
            name='code',
            field=models.CharField(choices=[('USD', 'Dólar Americano'), ('BTC', 'Bitcoin'), ('EUR', 'Euro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='investmentoffer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investmentoffer',
            name='index_variable',
            field=models.CharField(choices=[('IPCA', 'Inflação'), ('SELIC', 'Selic'), ('CDI', 'Cdi')], max_length=10),
        ),
        migrations.AlterField(
            model_name='investmentoffer',
            name='min_value',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='investmentoffer',
            name='percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
