# Generated by Django 5.2 on 2025-08-01 19:18

import offers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_alter_investmentoffer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentoffer',
            name='min_value',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[offers.models.validate_gte_0]),
        ),
    ]
