# Generated by Django 5.2 on 2025-08-01 19:25

import offers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_alter_investmentoffer_min_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentoffer',
            name='percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[offers.models.validate_gte_0]),
        ),
    ]
