# Generated by Django 5.2 on 2025-08-10 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_cnpj'),
        ('offers', '0008_alter_investmentoffer_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentoffer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
