# Generated by Django 5.2 on 2025-08-17 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
        ('offers', '0009_alter_investmentoffer_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentoffer',
            name='code',
        ),
        migrations.RemoveField(
            model_name='investmentoffer',
            name='index_variable',
        ),
        migrations.AddField(
            model_name='investmentoffer',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='investmentoffer',
            name='monetary_index',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='finances.monetaryindex'),
            preserve_default=False,
        ),
    ]
