# Generated by Django 5.2 on 2025-05-06 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='offert',
            old_name='coin',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='offert',
            old_name='fees',
            new_name='min_value',
        ),
        migrations.RenameField(
            model_name='offert',
            old_name='value',
            new_name='percent',
        ),
        migrations.AddField(
            model_name='transaction',
            name='value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('USD', 'Dólar'), ('BTC', 'Bitcoin'), ('EUR', 'Euro')], max_length=10)),
                ('balance', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
