# Generated by Django 5.2 on 2025-05-06 23:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_company_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedBacks',
            new_name='FeedBack',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone',
        ),
    ]
