# Generated by Django 5.2 on 2025-05-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('USD', 'Dólar'), ('BTC', 'Bitcoin'), ('EUR', 'Euro')], max_length=10)),
                ('balance', models.FloatField(default=0)),
            ],
        ),
    ]
