# Generated by Django 5.2 on 2025-08-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_account_unique_code_per_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(choices=[('USD', 'Dólar Americano'), ('BTC', 'Bitcoin'), ('EUR', 'Euro')], max_length=10),
        ),
    ]
