# Generated by Django 5.2 on 2025-08-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_balance'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='unique_code_per_user',
        ),
        migrations.RemoveField(
            model_name='account',
            name='code',
        ),
    ]
