# Generated by Django 5.2 on 2025-08-17 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_balance'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='code',
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='finances.monetaryindex'),
            preserve_default=False,
        ),
    ]
