# Generated by Django 5.2 on 2025-08-17 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_account_currency'),
        ('finances', '0002_populate_currency_monetary_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=['created_by', 'currency'], name='unique_currency_per_user'),
        ),
    ]
