# Generated by Django 5.2 on 2025-05-15 17:42

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('CNPJ', models.CharField(max_length=20, unique=True, validators=[companies.models.validate_cnpj])),
            ],
        ),
    ]
