# Generated by Django 5.2 on 2025-07-18 02:02

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='CNPJ',
            field=models.CharField(max_length=20, unique=True, validators=[companies.models.validate_len, companies.models.validate_digit]),
        ),
    ]
